# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



jobs:
  build:
    if: "! contains(github.event.head_commit.message, 'skip:tests')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Tests
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Git Branch
      run: git pull

    - name: java home
      run: echo $JAVA_HOME

    - name: current directory
      run: pwd

    - name: current directory content
      run: ls -lrt
    - name: create artifacts folder
      run: mkdir -p artifacts


    - name: find iflow changes
      run: |
            chmod +x ./.github/workflows/zipiflows.sh
            ./.github/workflows/zipiflows.sh

    - name: List the iFlows going to tested.
      run: ls -lah artifacts/

    - name: get the cplink test script test cases
      run: |
            wget https://github.com/mwittrock/cpilint/releases/download/v1.0.4/cpilint-1.0.4.zip
            unzip cpilint-1.0.4.zip
            chmod +x ./cpilint-1.0.4/bin/cpilint

    - name: Executing tests on iFlow
      run: ./cpilint-1.0.4/bin/cpilint -rules cpilintrulesnew.xml -files MessageMappingFunctions1.zip
