# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant.

name: CPILint

on:
  push:
    branches: [ irtsync ]
  pull_request:
    branches: [ irtsync ]


jobs:
  build:
    if: "! contains(github.event.head_commit.message, 'skip:tests')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Tests
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Git Branch
      run: git pull

    - name: java home
      run: echo $JAVA_HOME

    - name: current directory
      run: pwd

    - name: current directory content
      run: ls -lrt
    - name: create artifacts folder
      run: mkdir -p artifacts


    - name: find iflow changes
      run: |
            chmod +x ./.github/workflows/zipiflows.sh
            ./.github/workflows/zipiflows.sh

    - name: List the iFlows going to tested.
      run: ls -lah artifacts/

    - name: get the cplink test script test cases
      run: |
            wget https://github.com/mwittrock/cpilint/releases/download/v1.0.4/cpilint-1.0.4.zip
            unzip cpilint-1.0.4.zip
            chmod +x ./cpilint-1.0.4/bin/cpilint

    - name: Executing tests on iFlow
      run: ./cpilint-1.0.4/bin/cpilint -rules cpilint.xml -directory artifacts/
